"""
ORM Model: AI Recommendation
Context-aware action recommendations generated by the AI engine.
"""

from datetime import datetime
from sqlalchemy import String, Float, Integer, DateTime, ForeignKey, Text, JSON, Boolean
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import Base


class Recommendation(Base):
    __tablename__ = "recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    location_id: Mapped[int] = mapped_column(Integer, ForeignKey("locations.id"), nullable=True)
    alert_id: Mapped[int] = mapped_column(Integer, ForeignKey("alerts.id"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, index=True)

    category: Mapped[str] = mapped_column(String(100), nullable=False)  # health/industrial/policy/traffic
    priority: Mapped[str] = mapped_column(String(20), default="Medium")  # Low/Medium/High/Urgent
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    action_steps: Mapped[dict] = mapped_column(JSON, nullable=True)   # list of steps
    affected_population: Mapped[str] = mapped_column(Text, nullable=True)
    expected_impact: Mapped[str] = mapped_column(Text, nullable=True)
    time_horizon: Mapped[str] = mapped_column(String(50), nullable=True)  # immediate/short-term/long-term
    source_data_summary: Mapped[str] = mapped_column(Text, nullable=True)
    confidence_score: Mapped[float] = mapped_column(Float, nullable=True)  # 0-1
    is_automated: Mapped[bool] = mapped_column(Boolean, default=True)

    def __repr__(self):
        return f"<Recommendation id={self.id} category='{self.category}' priority='{self.priority}'>"
